version: '3.9'
services:

  influxdb:
    image: influxdb:2.4.0
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=exampletoken

  data_loader:
    depends_on: 
      - influxdb
    build: server/data

  api:
    depends_on:
      - influxdb
    build: server
    ports:
      - "80:80"
  
