version: "3.8"
services:
  web: 
    build: ./web
    ports: 
      - 3000:3000

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=beegroup
      - POSTGRES_DB=mydb