version: "3.7"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
