version: '3'

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
